#!/bin/bash
# Script'in bulunduğu dizini almak için
script_dir=$(dirname "${BASH_SOURCE[0]}")

cd $script_dir
lex kemal.l
yacc -d kemal.y
g++ -g -o calculator lex.yy.c y.tab.c -lm -Wno-deprecated
rm y.tab.c y.tab.h lex.yy.c
if [ "$#" -eq 0 ]; then
	./calculator
else
	./calculator < $1 > kemal.cpp
fi
g++ kemal.cpp -o calculator
# rm kemal.cpp
./calculator
rm calculator
